### ISSUE TITLE
ERROR:Launch file 

### ISSUE THREAD

**Issue by shuto1441** [shuto1441/dobot#2]
If the following command is done
`roslaunch dobot dobot.launch portname:="/dev/ttyUSB1"`

the following error is displayed.
It has been confirmed that the port number is correct.
`Invalid port name or Dobot is occupied by other application!
[dobot_server-2] process has died [pid 56560, exit code 253, cmd /home/ishii/dobot_ws/devel/lib/dobot/DobotServer __name:=dobot_server __log:=/home/ishii/.ros/log/2e366376-483b-11ec-a0f6-7f962babd124/dobot_server-2.log].
log file: /home/ishii/.ros/log/2e366376-483b-11ec-a0f6-7f962babd124/dobot_server-2*.log
`

**Comment by tongtybj** [comment]
Please do not add  `"`  when you assign the port:

roslaunch dobot dobot.launch portname:=/dev/ttyUSB1

**Comment by shuto1441** [comment]
@tongtybj 
When I run that command, I get the same error

**Comment by tongtybj** [comment]
Please run `$ ls /dev | grep ttyUSB` to check which port is available. (I mean the correct port is maybe `/dev/ttyUSB0`)

**Comment by shuto1441** [comment]
Thank you. I confirmed the correct port．
But I get the same result by running the following command.
`roslaunch dobot dobot.launch portname:=/dev/ttyUSB0`

**Comment by tongtybj** [comment]
BTW, I am curious why  you assigned `portname:=/dev/ttyUSB1` at your first time.

**Comment by tongtybj** [comment]
The error said: `Invalid port name or Dobot is occupied by other application!`

- please confirm `/dev/ttyUSB0` is related to dobot. Unplug the dobot USB cable, the port will disappear from `/dev`
- please make sure there is no any other process about dobot runing at the same time.
