### ISSUE TITLE
About python symbolic link in Ubuntu20.04

### ISSUE THREAD

**Issue by tongtybj** [shuto1441/dobot#5]
@shuto1441 

This is a fastest solution for the problem raised in https://github.com/shuto1441/dobot/pull/4#issuecomment-978773327

```
$ sudo apt install python-is-python3
```

Please read https://qiita.com/sho1_24/items/96c3c9e71629de3801fb#os%E6%A8%99%E6%BA%96%E3%81%AEpython%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%81%B8%E3%81%AE%E3%82%B7%E3%83%B3%E3%83%9C%E3%83%AA%E3%83%83%E3%82%AF%E3%83%AA%E3%83%B3%E3%82%AF%E4%BD%9C%E6%88%90

**Comment by shuto1441** [comment]
Thank you very much.
It now works in my env.

**Comment by tongtybj** [comment]
Great!

I think this is best way to solve the remained problem in #4.
Otherwise, I have to write several lines to install python3 based dependencies for Ubuntu18.04 env. 
Now, we only have to announce users of Ubuntu20.04 to execute above single command.
